---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kitchenowl.fullname"}}-pvc
spec:
  accessModes:
    - {{ .Values.persistance.accessModes }}
  storageClassName: {{ .Values.persistance.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistance.size }}
