---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kitchenowl.fullname" . }}
  labels:
  {{ include "kitchenowl.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
